#!/bin/bash


set -e

echo "Running from $(pwd)"

which pebl > /dev/null 2>&1 && true

if [ $? -ne 0 ]
then
	PBLEXE="/cygdrive/c/Users/simonh/home/dlh/PEBLPortable0.14/PEBLPortable/PEBL/bin/pebl.exe"
else
	PBLEXE=$(which pebl)
fi

if [ ! -f $PBLEXE ]
then
	echo "Couldn't find $PBLEXE"
	exit -1
fi


echo "Using pebl exe:"
echo "$PBLEXE"


XSPANPBL="xspan.pbl"

if [ ! -f $XSPANPBL ]
then
	XSPANPBL="/cygdrive/c/Users/simonh/home/dlh/src/PEBLPortable/xspan.pbl"
	if [ -f '/usr/bin/cygpath' ]
	then
		# make work on cygwin - unix on windows
		XSPANPBL=$(cygpath -aw $XSPANPBL)
	fi
fi

if [ ! -f $XSPANPBL ]
then
	echo "Couldn't find $XSPANPBL"
	exit -1
fi

echo "Using pebl script:"
echo "$XSPANPBL"

$PBLEXE --fullscreen -V testtype=symspan -V distract=distraction_symspan.txt $XSPANPBL
